version: '3.9'
services:
  api:
    env_file:
      - ./.env
    image: quiron:latest
    container_name: quiron-api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:80
      - 5003:443
    volumes:
      - ./Certificado:/app/Certificado
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - Kestrel__Certificates__Default__Password=1234
      - Kestrel__Certificates__Default__Path=/app/Certificado/CertificadoVisualStudio.pfx
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "https://10.0.0.131:5002/HealthCheck/Check"
        ]
      retries: 3
      interval: 5s
      timeout: 10s
      start_period: 10s